version: "3.9"
services:
  apiService:
    image: "retrogamesapi"
    container_name: "retroapi"
    environment:
      - host=apiDB
      - apiHost = api_host
      - apiPort = api_port
  apiDB:
    image: "mongo:latest"
    container_name: "apiDB"
    ports:
      - "2717:27017"